name: Bug Report
description: Create a report to help reproduce and fix the issue.
body:
  - type: markdown
    attributes:
      value: |
        # **Please read the following guidelines. Follow all instructions or else your issue is subject to closure.**
        ## If you use the "Report Issue" button in the top-right corner of the game, it will automatically fill in some of the information below.

        If you are reporting an issue found in another branch or codebase, you _must_ link the branch or codebase repo in your issue report or it will be closed.
        For branches, If you have not pushed your code up, please either reproduce it on master or push your code up before making an issue report.
        For other codebases, if you do not have a public code repository you will be refused help unless you can completely reproduce the issue on our master branch.
  - type: input
    id: reporting-version
    attributes:
      label: "Client Version:"
      description: |
        The BYOND version you are using to report this issue. You can find this information in the bottom left corner of the "About BYOND" window in the BYOND client.
        It is strongly recommended that you include this, especially for concerns on the visual aspects of the game.
      placeholder: "xxx.xxxx"
    validations:
      required: false
  - type: textarea
    id: issue-summary
    attributes:
      label: "Issue Summary:"
      description: |
        Briefly explain your issue in a few plain sentences. You may copy and paste the issue title here if it is suitable.
      placeholder: |
        "When I do X, Y happens instead of Z."
        "X on Y map has Z issue."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction Steps:"
      description: |
        Describe the steps to reproduce the issue in detail. Include any relevant information, such as the map, round type, and any other factors that may be relevant.
        If it is a runtime-related error, please include the runtime here as that is pertient information. Issues are not for oddities introduced by admin varedits, ensure these occur in normal circumstances.
      placeholder: |
        1. Go to the X location
        2. Do Y action
        3. Observe Z result
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # **If there is a screenshot or video, please place it here to better explain the problem.**
